# Usa la imagen base desde Docker Hub
FROM jian720/mongo

# Exponemos el puerto 3306 para que se pueda acceder a MySQL desde fuera del contenedor
EXPOSE 27017

# Establecemos las variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=root

